name: Run the tests

on:
  push:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  run_the_tests:
    name: Run the tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install poetry
        run: pipx install poetry==1.3.2

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install python dependencies
        run: poetry install

      - name: Run the tests
        run: poetry run pytest tests --cov=./pvconsumer --cov-report=xml
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SYSTEM_ID: ${{ secrets.SYSTEM_ID }}
          DATA_SERVICE_URL: https://pvoutput.org/
          SS_KEY: ${{ secrets.SS_KEY }}
          SS_URL: ${{ secrets.SS_URL }}
          SS_USER_ID: ${{ secrets.SYSTEMSS_USER_ID_ID }}


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
