name: Run the tests

on:
  push:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  run_the_tests:
    name: Run the tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run the tests
        # Using --maxfail 1 because the tests are quite slow.
        run: pytest tests --cov=./pvconsumer --cov-report=xml --maxfail 1 -m "not liveapi"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
